# .travis.yml for cartogram.
language: r

matrix:
  include:
    - dist: trusty
      before_install:
        - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
        - sudo apt-get --yes --force-yes update -qq
        # sf dependencies:
        - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
      r: oldrel
      sudo: required
    - os: osx
      osx_image: xcode9.2
      disable_homebrew: true
      r: 

r:
  - release
  - devel

cache: packages

apt_packages:
  - libgdal-dev
  - libproj-dev

notifications:
email:
on_success: change
on_failure: change
